function foo1(){
var c1=document.getElementById('c1');
 c1.onclick=function foo(){
    document.getElementById('n1').value= this.innerHTML=document.getElementById('n3').value+' Mde/Mrs vous avez choisir "YASSA et boir QUELLES CHOSE et de payer avec  ' + document.getElementById('modePay').value;
    document.getElementById('n2').value=this.innerHTML =' le montant s eleve a :2500'
      this.innerHTML='BRAVooooo!'
 };
};
function foo2(){
    var c1=document.getElementById('c2');
     c1.onclick=function foo(){
        document.getElementById('n1').value=document.getElementById('n3').value+' Mde/Mrs vous avez choisir : riz au poisson et de payer avec  ' + document.getElementById('modePay').value;
        document.getElementById('n2').value =' le montant s eleve a :2000';
        this.innerHTML='bingooooo!'
    
     };
    };
    function foo3(){
        var c3=document.getElementById('c3');
         c3.onclick=function foo(){
            document.getElementById('n1').value=document.getElementById('n3').value+' Mde/Mrs vous avez choisir :maffe et de payer avec ' + document.getElementById('modePay').value;
            document.getElementById('n2').value =' le montant s eleve a :1500';
      this.innerHTML='YOUPIIIIII!'
        
         };
        };
        function foo4(){
         var c4=document.getElementById('c4');
          c4.onclick=function foo(){
             document.getElementById('n1').value=document.getElementById('n3').value+' Mde/Mrs vous avez choisir :maffe et pour boir coca cola  et de payer avec ' + document.getElementById('modePay').value;
             document.getElementById('n2').value =' le montant s eleve a :1700';
             this.innerHTML='WELLIIII!'
         
          };
         };
         function foo5(){
            var c5=document.getElementById('c5');
             c5.onclick=function foo(){
                document.getElementById('n1').value=document.getElementById('n3').value+' Mde/Mrs vous avez choisir :OMLET ET DU COFEE et de payer avec '+ document.getElementById('modePay').value;
                document.getElementById('n2').value =' le montant s eleve a :1400';
                this.innerHTML='GENIALLLL!'
            
     };
 };  
            function foo6(){
               var c6=document.getElementById('c6');
                c6.onclick=function foo(){
                   document.getElementById('n1').value=document.getElementById('n3').value+' Mde/Mrs vous avez choisir :riz au poisson + jus de fruit  et de payer avec '+ document.getElementById('modePay').value;
                   document.getElementById('n2').value =' le montant s eleve a :1600';
                   this.innerHTML='SUPERRRR!'
               
                };
               };                         

function b11(){
   var para1= document.getElementById('gter1');
   var para2=document.getElementById('gter2');
   para1.onclick=function(){
      this.innerHTML='nous sommes meilleur dans noter.nous somme bien qualifier dans ce dommain.nous participons a la developpement de notre pays en participant ala reduction du chaumage des geunnes.La satisfaction de nos clients est noter objectif .'
   };
   para2.onclick=function(){
      this.innerHTML='une entreprise exempilair au geunnes africaine .L ideal general en est de monter qu on peut naitre ici travailler ici et reussir .'

   }
}     